using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using EquiBillBook.Helpers;

namespace EquiBillBook.Models
{
    public class ClsData
    {
        public decimal PointsEarned { get; set; }
        public decimal TaxPercent { get; set; }
        public long TotalCount { get; set; }
        public long ActiveCount { get; set; }
        public long InactiveCount { get; set; }
        public long PendingCount { get; set; }
        public decimal TotalNilAmount { get; set; }
        public decimal TotalExemptedAmount { get; set; }
        public decimal TotalNonGstAmount { get; set; }
        public decimal TotalInvoiceValue { get; set; }
        public decimal TotalTaxableValue { get; set; }
        public decimal TotalIgstValue { get; set; }
        public decimal TotalCgstValue { get; set; }
        public decimal TotalSgstValue { get; set; }
        public decimal TotalUtgstValue { get; set; }
        public decimal TotalCessValue { get; set; }
        public long UploadedCount { get; set; }
        public long RejectedCount { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public int MonthsLeft { get; set; }
        public decimal TotalSales { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal TotalCreditSales { get; set; }
        public decimal TotalChangeReturn { get; set; }
        public decimal TotalRefund { get; set; }
        public int PageSize { get; set; }
        public decimal StockValueBySalesPrice { get; set; }
        public decimal StockValueByPurchasePrice { get; set; }
        public decimal PotentialProfit { get; set; }
        public decimal ProfitMargin { get; set; }
        public decimal NetProfitLoss { get; set; }
        public int MinPrice { get; set; }
        public int MaxPrice { get; set; }
        public ClsRoleVm Role { get; set; }
        public IList<ClsRoleVm> Roles { get; set; }
        public ClsUserVm User { get; set; }
        public IList<ClsUserVm> Users { get; set; }
        public IList<ClsUserVm> UserReport { get; set; }
        public ClsBranchVm Branch { get; set; }
        public IList<ClsBranchVm> Branchs { get; set; }
        public ClsBrandVm Brand { get; set; }
        public IList<ClsBrandVm> Brands { get; set; }
        public ClsCategoryVm Category { get; set; }
        public IList<ClsCategoryVm> Categories { get; set; }
        public ClsSubCategoryVm SubCategory { get; set; }
        public IList<ClsSubCategoryVm> SubCategories { get; set; }
        public ClsSubSubCategoryVm SubSubCategory { get; set; }
        public IList<ClsSubSubCategoryVm> SubSubCategories { get; set; }
        public ClsCountryVm Country { get; set; }
        public IList<ClsCountryVm> Countrys { get; set; }
        public ClsStateVm State { get; set; }
        public IList<ClsStateVm> States { get; set; }
        public IList<ClsStateVm> AltStates { get; set; }
        public ClsCityVm City { get; set; }
        public IList<ClsCityVm> Citys { get; set; }
        public IList<ClsCityVm> AltCitys { get; set; }
        public ClsUserGroupVm UserGroup { get; set; }
        public IList<ClsUserGroupVm> UserGroups { get; set; }
        public ClsCurrencyVm Currency { get; set; }
        public IList<ClsCurrencyVm> Currencys { get; set; }
        public ClsWarrantyVm Warranty { get; set; }
        public IList<ClsWarrantyVm> Warrantys { get; set; }
        public ClsReligionVm Religion { get; set; }
        public IList<ClsReligionVm> Religions { get; set; }
        public ClsVariationVm Variation { get; set; }
        public IList<ClsVariationVm> Variations { get; set; }
        public ClsTaxVm Tax { get; set; }
        public IList<ClsTaxVm> Taxs { get; set; }
        public ClsUnitVm Unit { get; set; }
        public IList<ClsUnitVm> Units { get; set; }
        public ClsPaymentTypeVm PaymentType { get; set; }
        public IList<ClsPaymentTypeVm> PaymentTypes { get; set; }
        public ClsVariationDetailsVm VariationDetail { get; set; }
        public IList<ClsVariationDetailsVm> VariationDetails { get; set; }
        public ClsItemVm Item { get; set; }
        public IList<ClsItemVm> Items { get; set; }
        public string[] ItemsArray { get; set; }
        public ClsItemDetailsVm ItemDetail { get; set; }
        public IList<ClsItemDetailsVm> ItemDetails { get; set; }
        public ClsPurchaseQuotationVm PurchaseQuotation { get; set; }
        public IList<ClsPurchaseQuotationVm> PurchaseQuotations { get; set; }
        public ClsPurchaseQuotationDetailsVm PurchaseQuotationDetail { get; set; }
        public IList<ClsPurchaseQuotationDetailsVm> PurchaseQuotationDetails { get; set; }
        public ClsPurchaseOrderVm PurchaseOrder { get; set; }
        public IList<ClsPurchaseOrderVm> PurchaseOrders { get; set; }
        public ClsPurchaseOrderDetailsVm PurchaseOrderDetail { get; set; }
        public IList<ClsPurchaseOrderDetailsVm> PurchaseOrderDetails { get; set; }
        public ClsPurchaseVm Purchase { get; set; }
        public IList<ClsPurchaseVm> Purchases { get; set; }
        public ClsPurchaseDetailsVm PurchaseDetail { get; set; }
        public IList<ClsPurchaseDetailsVm> PurchaseDetails { get; set; }
        public ClsExpenseVm Expense { get; set; }
        public IList<ClsExpenseVm> Expenses { get; set; }
        public ClsPurchaseReturnVm PurchaseReturn { get; set; }
        public IList<ClsPurchaseReturnVm> PurchaseReturns { get; set; }
        public ClsPurchaseReturnDetailsVm PurchaseReturnDetail { get; set; }
        public IList<ClsPurchaseReturnDetailsVm> PurchaseReturnDetails { get; set; }
        public ClsStockAdjustmentVm StockAdjustment { get; set; }
        public IList<ClsStockAdjustmentVm> StockAdjustments { get; set; }
        public ClsStockAdjustmentDetailsVm StockAdjustmentDetail { get; set; }
        public IList<ClsStockAdjustmentDetailsVm> StockAdjustmentDetails { get; set; }
        public ClsStockTransferVm StockTransfer { get; set; }
        public IList<ClsStockTransferVm> StockTransfers { get; set; }
        public ClsStockTransferDetailsVm StockTransferDetail { get; set; }
        public IList<ClsStockTransferDetailsVm> StockTransferDetails { get; set; }
        public ClsSalesQuotationVm SalesQuotation { get; set; }
        public IList<ClsSalesQuotationVm> SalesQuotations { get; set; }
        public ClsSalesQuotationDetailsVm SalesQuotationDetail { get; set; }
        public IList<ClsSalesQuotationDetailsVm> SalesQuotationDetails { get; set; }
        public ClsSalesOrderVm SalesOrder { get; set; }
        public IList<ClsSalesOrderVm> SalesOrders { get; set; }
        public ClsSalesOrderDetailsVm SalesOrderDetail { get; set; }
        public IList<ClsSalesOrderDetailsVm> SalesOrderDetails { get; set; }
        public ClsSalesProformaVm SalesProforma { get; set; }
        public IList<ClsSalesProformaVm> SalesProformas { get; set; }
        public ClsSalesProformaDetailsVm SalesProformaDetail { get; set; }
        public IList<ClsSalesProformaDetailsVm> SalesProformaDetails { get; set; }
        public ClsDeliveryChallanVm DeliveryChallan { get; set; }
        public IList<ClsDeliveryChallanVm> DeliveryChallans { get; set; }
        public ClsDeliveryChallanDetailsVm DeliveryChallanDetail { get; set; }
        public IList<ClsDeliveryChallanDetailsVm> DeliveryChallanDetails { get; set; }
        public ClsSalesVm Sale { get; set; }
        public IList<ClsSalesVm> Sales { get; set; }
        public ClsSalesDetailsVm SalesDetail { get; set; }
        public IList<ClsSalesDetailsVm> SalesDetails { get; set; }
        public ClsOpeningStockVm OpeningStock { get; set; }
        public IList<ClsOpeningStockVm> OpeningStocks { get; set; }
        public ClsSalesReturnVm SalesReturn { get; set; }
        public IList<ClsSalesReturnVm> SalesReturns { get; set; }
        public ClsSalesReturnDetailsVm SalesReturnDetail { get; set; }
        public IList<ClsSalesReturnDetailsVm> SalesReturnDetails { get; set; }
        public ClsMenuVm Menu { get; set; }
        public IList<ClsMenuVm> Menus { get; set; }
        public ClsMenuPermissionVm MenuPermission { get; set; }
        public IList<ClsMenuPermissionVm> MenuPermissions { get; set; }
        public string[] UsersArray { get; set; }
        public ClsLoginDetailsVM LoginDetail { get; set; }
        public IList<ClsLoginDetailsVM> LoginDetails { get; set; }
        public ClsDashboard Dashboard { get; set; }
        public ClsStock Stock { get; set; }
        public List<ClsPurchaseSales> PurchaseSales { get; set; }
        public ClsPurchaseSales PurchaseSale { get; set; }
        public IList<ClsBalanceSheet> BalanceSheet { get; set; }
        public IList<ClsPrefixMasterVm> PrefixMasters { get; set; }
        public ClsPrefixMasterVm PrefixMaster { get; set; }
        public IList<ClsActivityLogVm> ActivityLogs { get; set; }
        public ClsBusinessSettingsVm BusinessSetting { get; set; }
        public ClsItemSettingsVm ItemSetting { get; set; }
        public ClsSaleSettingsVm SaleSetting { get; set; }
        public ClsPosSettingsVm PosSetting { get; set; }
        public ClsPurchaseSettingsVm PurchaseSetting { get; set; }
        public ClsRewardPointSettingsVm RewardPointSetting { get; set; }
        public ClsShortCutKeySettingVm ShortCutKeySetting { get; set; }
        public List<ClsShortCutKeySettingVm> ShortCutKeySettings { get; set; }
        public ClsAddressVm Addresses { get; set; }
        public List<ClsAddressVm> Address { get; set; }
        public ClsSellingPriceGroupVm SellingPriceGroup { get; set; }
        public List<ClsSellingPriceGroupVm> SellingPriceGroups { get; set; }
        public List<ClsPlanVm> Plans { get; set; }
        public List<ClsTermLengthVm> TermLengths { get; set; }
        public List<ClsPlanAddonsVm> PlanAddons { get; set; }
        public ClsTransactionVm Transaction { get; set; }
        public IList<ClsTransactionVm> Transactions { get; set; }
        public ClsTransactionDetailsVm TransactionDetail { get; set; }
        public IList<ClsTransactionDetailsVm> TransactionDetails { get; set; }
        public ClsMyPlan MyPlan { get; set; }
        public ClsFeedbackVm Feedback { get; set; }
        public List<ClsFeedbackVm> Feedbacks { get; set; }
        public ClsSupportTicketVm SupportTicket { get; set; }
        public List<ClsSupportTicketVm> SupportTickets { get; set; }
        public ClsAccountTypeVm AccountType { get; set; }
        public IList<ClsAccountTypeVm> AccountTypes { get; set; }
        public ClsAccountSubTypeVm AccountSubType { get; set; }
        public IList<ClsAccountSubTypeVm> AccountSubTypes { get; set; }
        public ClsAccountVm Account { get; set; }
        public IList<ClsAccountVm> Accounts { get; set; }
        public ClsAccountDetailsVm AccountDetail { get; set; }
        public IList<ClsAccountDetailsVm> AccountDetails { get; set; }
        public ClsCashRegisterVm CashRegister { get; set; }
        public IList<ClsCashRegisterVm> CashRegisters { get; set; }
        public ClsTimeZoneVm TimeZone { get; set; }
        public IList<ClsTimeZoneVm> TimeZones { get; set; }
        public ClsSecondaryUnitVm SecondaryUnit { get; set; }
        public IList<ClsSecondaryUnitVm> SecondaryUnits { get; set; }
        public ClsTertiaryUnitVm TertiaryUnit { get; set; }
        public IList<ClsTertiaryUnitVm> TertiaryUnits { get; set; }
        public ClsQuaternaryUnitVm QuaternaryUnit { get; set; }
        public IList<ClsQuaternaryUnitVm> QuaternaryUnits { get; set; }
        public IList<ClsNotificationModulesVm> NotificationModules { get; set; }
        public IList<ClsNotificationModulesDetailsVm> NotificationModulesDetails { get; set; }
        public IList<ClsNotificationModulesSettingsVm> NotificationModulesSettings { get; set; }
        public ClsNotificationModulesSettingsVm NotificationModulesSetting { get; set; }
        public ClsNotificationModulesDetailsVm NotificationModulesDetail { get; set; }
        public ClsNotificationTemplatesVm NotificationTemplate { get; set; }
        public List<ClsNotificationTemplatesVm> NotificationTemplates { get; set; }
        public ClsSmsSettingsVm SmsSetting { get; set; }
        public IList<ClsSmsSettingsVm> SmsSettings { get; set; }
        public ClsEmailSettingsVm EmailSetting { get; set; }
        public IList<ClsEmailSettingsVm> EmailSettings { get; set; }
        public ClsPageSeoSettingsVm PageSeoSettings { get; set; }
        public IList<ClsPageSeoSettingsVm> PageSeoSettingsList { get; set; }
        public ClsWhatsappSettingsVm WhatsappSetting { get; set; }
        public IList<ClsWhatsappSettingsVm> WhatsappSettings { get; set; }
        public ClsOnlinePaymentSettingsVm OnlinePaymentSetting { get; set; }
        public IList<ClsOnlinePaymentSettingsVm> OnlinePaymentSettings { get; set; }
        public ClsDomainVm Domain { get; set; }
        public IList<ClsDomainVm> Domains { get; set; }
        public ClsCompetitorVm Competitor { get; set; }
        public IList<ClsCompetitorVm> Competitors { get; set; }
        public ClsIndustryTypeVm IndustryType { get; set; }
        public IList<ClsIndustryTypeVm> IndustryTypes { get; set; }
        public ClsBusinessTypeVm BusinessType { get; set; }
        public IList<ClsBusinessTypeVm> BusinessTypes { get; set; }
        public ClsSmsUsedVm SmsUsed { get; set; }
        public IList<ClsSmsUsedVm> SmsUseds { get; set; }
        public ClsEmailUsedVm EmailUsed { get; set; }
        public IList<ClsEmailUsedVm> EmailUseds { get; set; }
        public IList<ClsUserLogVm> UserLogs { get; set; }
        public IList<ClsItemLogVm> ClsItemLogs { get; set; }
        public IList<ClsPurchaseLogVm> PurchaseLogs { get; set; }
        public IList<ClsSaleLogVm> SaleLogs { get; set; }
        public IList<ClsPlaceLogVm> PlaceLogs { get; set; }
        public IList<ClsAccountLogVm> AccountLogs { get; set; }
        public IList<ClsBankLogVm> BankLogs { get; set; }
        public IList<ClsSettingLogVm> SettingLogs { get; set; }
        public IList<ClsOtherLogVm> OtherLogs { get; set; }
        public ClsSupportTicketDetailsVm SupportTicketDetail { get; set; }
        public IList<ClsSupportTicketDetailsVm> SupportTicketDetails { get; set; }
        public ClsTaxMapVm TaxMap { get; set; }
        public IList<ClsTaxMapVm> TaxMaps { get; set; }
        public ClsTaxReport TaxReport { get; set; }
        public ClsBranchPaymentTypeMapVm BranchPaymentTypeMap { get; set; }
        public ClsEnquiryVm Enquiry { get; set; }
        public ClsSellingPriceBranchMapVm SellingPriceBranchMap { get; set; }
        public ClsCouponVm Coupon { get; set; }
        public IList<ClsCouponVm> Coupons { get; set; }
        public IList<ClsCouponAddonVm> Addons { get; set; }
        public ClsResellerPaymentVm ResellerPayment { get; set; }
        public IList<ClsResellerPaymentVm> ResellerPayments { get; set; }
        public ClsResellerPaymentMethodVm ResellerPaymentMethod { get; set; }
        public IList<ClsResellerPaymentMethodVm> ResellerPaymentMethods { get; set; }
        public ClsStockAdjustmentDeductionIdVm StockAdjustmentDeductionId { get; set; }
        public IList<ClsStockAdjustmentDeductionIdVm> StockAdjustmentDeductionIds { get; set; }
        public ClsSalesDeductionIdVm SalesDeductionId { get; set; }
        public IList<ClsSalesDeductionIdVm> SalesDeductionIds { get; set; }
        public ClsStockTransferDeductionIdVm StockTransferDeductionId { get; set; }
        public IList<ClsStockTransferDeductionIdVm> StockTransferDeductionIds { get; set; }
        public ClsSalesReturnDeductionIdVm SalesReturnDeductionId { get; set; }
        public IList<ClsSalesReturnDeductionIdVm> SalesReturnDeductionIds { get; set; }
        public ClsLedgerDiscountVm LedgerDiscount { get; set; }
        public IList<ClsLedgerDiscountVm> LedgerDiscounts { get; set; }
        public ClsSupplierPaymentVm SupplierPayment { get; set; }
        public IList<ClsSupplierPaymentVm> SupplierPayments { get; set; }
        public ClsCustomerPaymentVm CustomerPayment { get; set; }
        public IList<ClsCustomerPaymentVm> CustomerPayments { get; set; }
        public ClsCustomerPaymentVm BookingPayment { get; set; }
        public IList<ClsCustomerPaymentVm> BookingPayments { get; set; }
        public IList<ClsCustomerPaymentVm> BookingRefunds { get; set; }
        public object OriginalPayment { get; set; }
        public ClsBankPaymentVm BankPayment { get; set; }
        public IList<ClsBankPaymentVm> BankPayments { get; set; }
        public ClsPrintLabelVm PrintLabel { get; set; }
        //public ClsCustomerPaymentDeductionIdVm CustomerPaymentDeductionId { get; set; }
        //public IList<ClsCustomerPaymentDeductionIdVm> CustomerPaymentDeductionIds { get; set; }
        //public ClsSupplierPaymentDeductionIdVm SupplierPaymentDeductionId { get; set; }
        //public IList<ClsSupplierPaymentDeductionIdVm> SupplierPaymentDeductionIds { get; set; }
        public IList<ClsOtherSoftwareImportVm> OtherSoftwareImports { get; set; }
        public IList<ClsAccountSubTypeMasterVm> AccountSubTypeMasters { get; set; }
        public IList<ClsAccountMasterVm> AccountMasters { get; set; }
        public ClsExpensePaymentVm ExpensePayment { get; set; }
        public IList<ClsExpensePaymentVm> ExpensePayments { get; set; }
        public ClsContraVm Contra { get; set; }
        public IList<ClsContraVm> Contras { get; set; }
        public ClsJournalVm Journal { get; set; }
        public IList<ClsJournalVm> Journals { get; set; }
        public ClsJournalPaymentVm JournalPayment { get; set; }
        public IList<ClsJournalPaymentVm> JournalPayments { get; set; }
        public ClsAccountSettingsVm AccountSetting { get; set; }
        public IList<ClsAccountSettingsVm> AccountSettings { get; set; }
        public ClsAccountOpeningBalanceVm AccountOpeningBalance { get; set; }
        public List<ClsAccountOpeningBalanceVm> AccountOpeningBalances { get; set; }
        public ClsHeaderVm Header { get; set; }
        public List<ClsHeaderVm> Headers { get; set; }
        public ClsPaymentLinkVm PaymentLink { get; set; }
        public List<ClsPaymentLinkVm> PaymentLinks { get; set; }
        public ClsPaymentTermVm PaymentTerm { get; set; }
        public List<ClsPaymentTermVm> PaymentTerms { get; set; }
        public ClsReminderModulesVm ReminderModule { get; set; }
        public List<ClsReminderModulesVm> ReminderModules { get; set; }
        public ClsReminderModulesDetailsVm ReminderModulesDetail { get; set; }
        public List<ClsReminderModulesDetailsVm> ReminderModulesDetails { get; set; }
        public ClsReminderModulesSettingsVm ReminderModulesSetting { get; set; }
        public List<ClsReminderModulesSettingsVm> ReminderModulesSettings { get; set; }
        public List<ClsStockDetails> StockDetails { get; set; }
        public IList<ClsTaxTypeVm> TaxTypes { get; set; }
        public ClsItemCodeVm ItemCode { get; set; }
        public List<ClsItemCodeVm> ItemCodes { get; set; }
        public ClsBusinessRegistrationNameVm BusinessRegistrationName { get; set; }
        public List<ClsBusinessRegistrationNameVm> BusinessRegistrationNames { get; set; }
        public ClsTaxExemptionVm TaxExemption { get; set; }
        public List<ClsTaxExemptionVm> TaxExemptions { get; set; }
        public ClsTaxSettingVm TaxSetting { get; set; }
        public List<ClsTaxSettingVm> TaxSettings { get; set; }
        public ClsPrefixVm Prefix { get; set; }
        public List<ClsPrefixVm> Prefixs { get; set; }
        public ClsPwaSettingsVm PwaSetting { get; set; }
        public List<ClsPwaSettingsVm> PwaSettings { get; set; }
        public ClsVehicleVm Vehicle { get; set; }
        public List<ClsVehicleVm> Vehicles { get; set; }
        public ClsExpenseSettingsVm ExpenseSetting { get; set; }
        public List<ClsExpenseTaxJournalVm> ExpenseTaxJournals { get; set; }
        public ClsExpenseTaxJournalVm ExpenseTaxJournal { get; set; }
        public List<ClsPurchaseTaxJournalVm> PurchaseTaxJournals { get; set; }
        public ClsPurchaseTaxJournalVm PurchaseTaxJournal { get; set; }
        public List<ClsSalesTaxJournalVm> SalesTaxJournals { get; set; }
        public ClsSalesTaxJournalVm SalesTaxJournal { get; set; }
        public List<ClsCustomerPaymentTaxJournalVm> CustomerPaymentTaxJournals { get; set; }
        public ClsCustomerPaymentTaxJournalVm CustomerPaymentTaxJournal { get; set; }
        public List<ClsSupplierPaymentTaxJournalVm> SupplierPaymentTaxJournals { get; set; }
        public ClsSupplierPaymentTaxJournalVm SupplierPaymentTaxJournal { get; set; }
        public List<ClsSalesReturnTaxJournalVm> SalesReturnTaxJournals { get; set; }
        public ClsSalesReturnTaxJournalVm SalesReturnTaxJournal { get; set; }
        public List<ClsPurchaseReturnTaxJournalVm> PurchaseReturnTaxJournals { get; set; }
        public ClsPurchaseReturnTaxJournalVm PurchaseReturnTaxJournal { get; set; }
        public List<ClsShippingBillVm> ShippingBills { get; set; }
        public ClsShippingBillVm ShippingBill { get; set; }
        public List<ClsShippingBillDetailsVm> ShippingBillDetails { get; set; }
        public ClsShippingBillDetailsVm ShippingBillDetail { get; set; }
        public List<ClsTaxDocuments> TaxDocuments { get; set; }
        public List<ClsSaltVm> Salts { get; set; }
        public ClsSaltVm Salt { get; set; }
        public string[] SaltsArray { get; set; }
        public List<ClsBillOfEntryVm> BillOfEntrys { get; set; }
        public ClsBillOfEntryVm BillOfEntry { get; set; }
        public List<ClsBillOfEntryDetailsVm> BillOfEntryDetails { get; set; }
        public ClsBillOfEntryDetailsVm BillOfEntryDetail { get; set; }
        public List<ClsStockAdjustmentReasonVm> StockAdjustmentReasons { get; set; }
        public ClsStockAdjustmentReasonVm StockAdjustmentReason { get; set; }
        public List<ClsStockTransferReasonVm> StockTransferReasons { get; set; }
        public ClsStockTransferReasonVm StockTransferReason { get; set; }
        public List<ClsSalesCreditNoteReasonVm> SalesCreditNoteReasons { get; set; }
        public ClsSalesCreditNoteReasonVm SalesCreditNoteReason { get; set; }
        public List<ClsSalesDebitNoteReasonVm> SalesDebitNoteReasons { get; set; }
        public ClsSalesDebitNoteReasonVm SalesDebitNoteReason { get; set; }
        public List<ClsPurchaseDebitNoteReasonVm> PurchaseDebitNoteReasons { get; set; }
        public ClsPurchaseDebitNoteReasonVm PurchaseDebitNoteReason { get; set; }
        public List<ClsUnitMasterVm> UnitMasters { get; set; }
        public ClsUnitMasterVm UnitMaster { get; set; }
        public List<ClsAdditionalChargeVm> AdditionalCharges { get; set; }
        public ClsAdditionalChargeVm AdditionalCharge { get; set; }
        public List<ClsSalesQuotationAdditionalChargesVm> SalesQuotationAdditionalCharges { get; set; }
        public ClsSalesQuotationAdditionalChargesVm SalesQuotationAdditionalCharge { get; set; }
        public List<ClsSalesOrderAdditionalChargesVm> SalesOrderAdditionalCharges { get; set; }
        public ClsSalesOrderAdditionalChargesVm SalesOrderAdditionalCharge { get; set; }
        public List<ClsSalesProformaAdditionalChargesVm> SalesProformaAdditionalCharges { get; set; }
        public ClsSalesProformaAdditionalChargesVm SalesProformaAdditionalCharge { get; set; }
        public List<ClsDeliveryChallanAdditionalChargesVm> DeliveryChallanAdditionalCharges { get; set; }
        public ClsDeliveryChallanAdditionalChargesVm DeliveryChallanAdditionalCharge { get; set; }
        public List<ClsSalesAdditionalChargesVm> SalesAdditionalCharges { get; set; }
        public ClsSalesAdditionalChargesVm SalesAdditionalCharge { get; set; }
        public List<ClsSalesReturnAdditionalChargesVm> SalesReturnAdditionalCharges { get; set; }
        public ClsSalesReturnAdditionalChargesVm SalesReturnAdditionalCharge { get; set; }
        public List<ClsPurchaseQuotationAdditionalChargesVm> PurchaseQuotationAdditionalCharges { get; set; }
        public ClsPurchaseQuotationAdditionalChargesVm PurchaseQuotationAdditionalCharge { get; set; }
        public List<ClsPurchaseOrderAdditionalChargesVm> PurchaseOrderAdditionalCharges { get; set; }
        public ClsPurchaseOrderAdditionalChargesVm PurchaseOrderAdditionalCharge { get; set; }
        public List<ClsPurchaseAdditionalChargesVm> PurchaseAdditionalCharges { get; set; }
        public ClsPurchaseAdditionalChargesVm PurchaseAdditionalCharge { get; set; }
        public List<ClsPurchaseReturnAdditionalChargesVm> PurchaseReturnAdditionalCharges { get; set; }
        public ClsPurchaseReturnAdditionalChargesVm PurchaseReturnAdditionalCharge { get; set; }
        public ClsPurchaseAdditionalTaxJournalVm PurchaseAdditionalTaxJournal { get; set; }
        public List<ClsPurchaseAdditionalTaxJournalVm> PurchaseAdditionalTaxJournals { get; set; }
        public ClsPurchaseReturnAdditionalTaxJournalVm PurchaseReturnAdditionalTaxJournal { get; set; }
        public List<ClsPurchaseReturnAdditionalTaxJournalVm> PurchaseReturnAdditionalTaxJournals { get; set; }
        public ClsSalesAdditionalTaxJournalVm SalesAdditionalTaxJournal { get; set; }
        public List<ClsSalesAdditionalTaxJournalVm> SalesAdditionalTaxJournals { get; set; }
        public ClsSalesReturnAdditionalTaxJournalVm SalesReturnAdditionalTaxJournal { get; set; }
        public List<ClsSalesReturnAdditionalTaxJournalVm> SalesReturnAdditionalTaxJournals { get; set; }
        public ClsItemCodeMasterVm ItemCodeMaster { get; set; }
        public List<ClsItemCodeMasterVm> ItemCodeMasters { get; set; }
        public ClsRecurringSalesVm RecurringSale { get; set; }
        public IList<ClsRecurringSalesVm> RecurringSales { get; set; }
        public ClsRecurringSalesDetailsVm RecurringSalesDetail { get; set; }
        public IList<ClsRecurringSalesDetailsVm> RecurringSalesDetails { get; set; }
        public List<ClsRecurringSalesAdditionalChargesVm> RecurringSalesAdditionalCharges { get; set; }
        public ClsRecurringSalesAdditionalChargesVm RecurringSalesAdditionalCharge { get; set; }
        public List<ClsCatalogueVm> Catalogues { get; set; }
        public ClsCatalogueVm Catalogue { get; set; }
        public List<ClsCatalogueItemVm> CatalogueItems { get; set; }
        public ClsCatalogueItemVm CatalogueItem { get; set; }
        public List<ClsCatalogueCategoryVm> CatalogueCategories { get; set; }
        public ClsCatalogueCategoryVm CatalogueCategory { get; set; }
        public List<ClsCatalogueBrandVm> CatalogueBrands { get; set; }
        public ClsCatalogueBrandVm CatalogueBrand { get; set; }
        public IList<ClsCustomerRewardPointsVm> CustomerRewardPoints { get; set; }
        public dynamic CustomerRewardPointsData { get; set; }
        public IList<ClsRewardPointTransactionVm> ExpiringPoints { get; set; }
        public ClsRewardPointTierVm RewardPointTier { get; set; }
        public IList<ClsRewardPointTierVm> RewardPointTiers { get; set; }
        public List<ClsPointsSummaryVm> Summary { get; set; }
        public ClsCustomerInfoVm Customer { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal ClosingBalance { get; set; }
        public ClsInvoiceTemplateVm Template { get; set; }
        public IList<ClsInvoiceTemplateVm> Templates { get; set; }
        public List<InvoiceTypeConfig> AvailableInvoiceTypes { get; set; }
        public ClsInvoiceTemplateDefaultsMasterVm Defaults { get; set; }
        public long InvoiceTemplateMasterId { get; set; }
        public List<ClsInvoiceTemplateLabelMasterVm> Labels { get; set; }
        
        // KOT System Properties
        public ClsKitchenStationVm Station { get; set; }
        public IList<ClsKitchenStationVm> Stations { get; set; }
        public IList<ClsCategoryVm> Categorys { get; set; }
        public List<long> CategoryIds { get; set; }
        public ClsKotMasterVm Kot { get; set; }
        public IList<ClsKotMasterVm> Kots { get; set; }
        public IList<ClsKotDetailsVm> KotDetails { get; set; }
        public ClsTableBookingVm Booking { get; set; }
        public IList<ClsTableBookingVm> Bookings { get; set; }
        public ClsRecurringBookingVm RecurringBooking { get; set; }
        public IList<ClsRecurringBookingVm> RecurringBookings { get; set; }
        public IList<ClsRestaurantTableVm> Tables { get; set; }
        public ClsRestaurantTableVm Table { get; set; }
        public IList<ClsRestaurantFloorVm> Floors { get; set; }
        public ClsRestaurantFloorVm Floor { get; set; }
        public IList<ClsTableTypeVm> TableTypes { get; set; }
        public ClsTableTypeVm TableType { get; set; }
        public IList<ClsStationTypeVm> StationTypes { get; set; }
        public ClsStationTypeVm StationType { get; set; }
        public ClsRestaurantSettingsVm RestaurantSettings { get; set; }
        public IList<object> RestaurantSettingsList { get; set; }
        public IList<ClsTableBookingVm> Events { get; set; }
        
        // Restaurant Dashboard Statistics Properties
        public ClsBookingStatsVm BookingStats { get; set; }
        public ClsKotStatsVm KotStats { get; set; }
        public ClsTableStatsVm TableStats { get; set; }
        public ClsRevenueStatsVm RevenueStats { get; set; }
        
        // Public Booking Response Properties
        public string BookingNo { get; set; }
        
        // QR Code properties for Restaurant Tables
        public string QrCodeImageUrl { get; set; }
        public string QrCodeUrl { get; set; }
        public long? TableId { get; set; }
        public string TableNo { get; set; }
        
        // Blog System Properties
        public ClsBlogVm Blog { get; set; }
        public IList<ClsBlogVm> Blogs { get; set; }
        public long PublishedCount { get; set; }
        public long UnpublishedCount { get; set; }
        public IList<ClsBlogVm> RelatedBlogs { get; set; }
        public ClsBlogCategoryVm BlogCategory { get; set; }
        public IList<ClsBlogCategoryVm> BlogCategories { get; set; }
        
        // Domain/Company Properties
        public long CompanyId { get; set; }
        
        // Booking Payment Properties
        public long BookingId { get; set; }
        
        // KOT Status Transition Report Properties
        public IList<dynamic> StatusTransitions { get; set; }
        
        // Staff Performance Report Properties
        public IList<dynamic> StaffPerformance { get; set; }
        
        // Individual Table Detail Report Properties
        public IList<dynamic> TableDetails { get; set; }
        
        // Booking Source Report Properties
        public IList<dynamic> SourceData { get; set; }
        
        // Table Performance Report Properties
        public IList<dynamic> TablePerformance { get; set; }
        
        // Table Type Performance Report Properties
        public IList<dynamic> TypePerformance { get; set; }
        
        // Customer Visit Frequency Report Properties
        public IList<dynamic> CustomerFrequency { get; set; }
    }
}