using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EquiBillBook.Models
{
    [Table("public.tblSalesProforma")]
    public class ClsSalesProforma
    {
        [Key]
        public long SalesProformaId { get; set; }
        public long BranchId { get; set; }
        public long CustomerId { get; set; }
        public long SellingPriceGroupId { get; set; }
        public DateTime SalesProformaDate { get; set; }
        public string Status { get; set; }
        public string InvoiceNo { get; set; }
        public int PayTermNo { get; set; }
        public int PayTerm { get; set; }
        public string AttachDocument { get; set; }
        public decimal Subtotal { get; set; }
        public long TaxId { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal Discount { get; set; }
        public string DiscountType { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal GrandTotal { get; set; }
        public string Notes { get; set; }        
        public string ShippingDetails { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingStatus { get; set; }
        public string DeliveredTo { get; set; }
        public string ShippingDocument { get; set; }
        public decimal TotalPaying { get; set; }
        public decimal Balance { get; set; }
        public decimal ChangeReturn { get; set; }
        public string HoldReason { get; set; }
        public string PaymentType { get; set; }
        public long CompanyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long AddedBy { get; set; }
        public DateTime AddedOn { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }        
        public long OnlinePaymentSettingsId { get; set; }
        public decimal ExchangeRate { get; set; }
        public long SmsSettingsId { get; set; }
        public long EmailSettingsId { get; set; }
        public long WhatsappSettingsId { get; set; }
        public string InvoiceId { get; set; }
        public long CashRegisterId { get; set; }
        public decimal RoundOff { get; set; }
        public decimal NetAmount { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public long UserGroupId { get; set; }
        public int IsInvoiced { get; set; }
        public long ReferenceId { get; set; }
        public string ReferenceType { get; set; }
        public long PlaceOfSupplyId { get; set; }
        public long TaxExemptionId { get; set; }
        public int IsBusinessRegistered { get; set; }
        public string GstTreatment { get; set; }
        public long BusinessRegistrationNameId { get; set; }
        public string BusinessRegistrationNo { get; set; }
        public string BusinessLegalName { get; set; }
        public string BusinessTradeName { get; set; }
        public string PanNo { get; set; }
        public long PrefixId { get; set; }
        public string PreviousStatus { get; set; }
        public decimal NetAmountReverseCharge { get; set; }
        public decimal RoundOffReverseCharge { get; set; }
        public decimal GrandTotalReverseCharge { get; set; }
        public decimal TaxableAmount { get; set; }
        public int IsReverseCharge { get; set; }
        public int PayTaxForExport { get; set; }
        public int TaxCollectedFromCustomer { get; set; }
        public decimal SpecialDiscount { get; set; }
        [AllowHtml]
        public string Terms { get; set; }
    }

    public class ClsSalesProformaVm
    {
        public long SalesProformaId { get; set; }
        public long CustomerId { get; set; }
        public long SellingPriceGroupId { get; set; }
        public long BranchId { get; set; }
        public DateTime SalesProformaDate { get; set; }
        public string Status { get; set; }
        public string InvoiceNo { get; set; }
        public int PayTermNo { get; set; }
        public int PayTerm { get; set; }
        public string AttachDocument { get; set; }
        public decimal Subtotal { get; set; }
        public long TaxId { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal Discount { get; set; }
        public string DiscountType { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal GrandTotal { get; set; }
        public string Notes { get; set; }        
        public string ShippingDetails { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingStatus { get; set; }
        public string DeliveredTo { get; set; }
        public string ShippingDocument { get; set; }
        public decimal TotalPaying { get; set; }
        public decimal Balance { get; set; }
        public decimal ChangeReturn { get; set; }
        public string HoldReason { get; set; }
        public string PaymentType { get; set; }
        public long CompanyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long AddedBy { get; set; }
        public DateTime AddedOn { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int PageSize { get; set; }
        public int PageIndex { get; set; }
        public string Search { get; set; }
        public string FileExtensionAttachDocument { get; set; }
        public List<ClsSalesQuotationDetailsVm> SalesQuotationDetails { get; set; }
        public List<ClsSalesOrderDetailsVm> SalesOrderDetails { get; set; }
        public List<ClsDeliveryChallanDetailsVm> DeliveryChallanDetails { get; set; }
        public List<ClsSalesProformaDetailsVm> SalesProformaDetails { get; set; }
        public List<ClsSalesDetailsVm> SalesDetails { get; set; }
        public ClsCustomerPaymentVm Payment { get; set; }
        public List<ClsCustomerPaymentVm> Payments { get; set; }
        public string FileExtensionShippingDocument { get; set; }
        public string UserType { get; set; }
        //public string Customer { get; set; }                
        public string MobileNo { get; set; }
        public string Title { get; set; }
        public string BusinessLogo { get; set; }
        public string BusinessName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Tax { get; set; }
        public string CustomerMobileNo { get; set; }
        public decimal Paid { get; set; }
        public decimal Due { get; set; }
        public decimal ReturnDue { get; set; }
        public bool IsSalesReturn { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        //public string Branch { get; set; }
        public string TaxNo { get; set; }
        public string Email { get; set; }
        public string CustomerEmailId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerMobile { get; set; }
        public string AddedByCode { get; set; }
        public string ModifiedByCode { get; set; }
        public string CustomerAltAddress { get; set; }
        public string IpAddress { get; set; }
        public string Browser { get; set; }
        public string Platform { get; set; }
        public string InvoiceUrl { get; set; }
        public ClsBusinessSettingsVm BusinessSetting { get; set; }
        public ClsBranchVm Branch { get; set; }
        //public List<ClsAddress> Addresses { get; set; }
        public string BranchName { get; set; }
        public bool IsShippingAddressDifferent { get; set; }
        public ClsUserVm User { get; set; }
        public long OnlinePaymentSettingsId { get; set; }
        public decimal ExchangeRate { get; set; }
        public string CurrencySymbol { get; set; }
        public string DefaultCurrencySymbol { get; set; }
        public long SmsSettingsId { get; set; }
        public long EmailSettingsId { get; set; }
        public long WhatsappSettingsId { get; set; }
        public List<ClsTaxVm> Taxs { get; set; }
        public bool IsAdvance { get; set; }
        public string InvoiceId { get; set; }
        public bool IsCredit { get; set; }
        public string Domain { get; set; }
        public long PaymentTypeId { get; set; }
        public decimal PaidQuantity { get; set; }
        public decimal FreeQuantity { get; set; }
        public long CashRegisterId { get; set; }
        public ClsCustomerPayment ChangeReturnPayment { get; set; }
        public decimal RoundOff { get; set; }
        public decimal NetAmount { get; set; }
        public string OtherRemarks { get; set; }
        public string Type { get; set; }
        public long SupplierId { get; set; }
        public decimal Credit { get; set; }
        public decimal Debit { get; set; }
        public long PaymentId { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public long UserGroupId { get; set; }
        public string SupplierName { get; set; }
        public string Page { get; set; }
        public long SalesQuotationId { get; set; }
        public long SalesOrderId { get; set; }
        public long DeliveryChallanId { get; set; }
        public int IsInvoiced { get; set; }
        public long ReferenceId { get; set; }
        public string ReferenceType { get; set; }
        public string Reference { get; set; }
        public bool CanEdit { get; set; }
        public long PlaceOfSupplyId { get; set; }
        public long CountryId { get; set; }
        public long BranchStateId { get; set; }
        public long TaxExemptionId { get; set; }
        public int IsBusinessRegistered { get; set; }
        public string GstTreatment { get; set; }
        public long BusinessRegistrationNameId { get; set; }
        public string BusinessRegistrationNo { get; set; }
        public string BusinessLegalName { get; set; }
        public string BusinessTradeName { get; set; }
        public string PanNo { get; set; }
        public long PrefixId { get; set; }
        public string PreviousStatus { get; set; }
        public int TotalItems { get; set; }
        public decimal NetAmountReverseCharge { get; set; }
        public decimal RoundOffReverseCharge { get; set; }
        public decimal GrandTotalReverseCharge { get; set; }
        public decimal TaxableAmount { get; set; }
        public int IsReverseCharge { get; set; }
        public int PayTaxForExport { get; set; }
        public int TaxCollectedFromCustomer { get; set; }
        public List<ClsSalesProformaAdditionalChargesVm> SalesProformaAdditionalCharges { get; set; }
        public List<ClsSalesAdditionalChargesVm> SalesAdditionalCharges { get; set; }
        public List<ClsSalesQuotationAdditionalChargesVm> SalesQuotationAdditionalCharges { get; set; }
        public List<ClsSalesOrderAdditionalChargesVm> SalesOrderAdditionalCharges { get; set; }
        public List<ClsDeliveryChallanAdditionalChargesVm> DeliveryChallanAdditionalCharges { get; set; }
        public decimal SpecialDiscount { get; set; }
        [AllowHtml]
        public string Terms { get; set; }
    }
}