using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EquiBillBook.Models
{
    [Table("public.tblSalesQuotationDetails")]
    public class ClsSalesQuotationDetails
    {
        [Key]
        public long SalesQuotationDetailsId { get; set; }
        public long SalesQuotationId { get; set; }
        public long ItemId { get; set; }
        public long ItemDetailsId { get; set; }
        public decimal Quantity { get; set; }
        public long TaxId { get; set; }
        public string DiscountType { get; set; }
        public decimal Discount { get; set; }
        public decimal UnitCost { get; set; }
        public decimal PriceIncTax { get; set; }
        public string OtherInfo { get; set; }
        public long CompanyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long AddedBy { get; set; }
        public DateTime AddedOn { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        //public string StockDeductionIds { get; set; }
        public decimal QuantityRemaining { get; set; }
        public long WarrantyId { get; set; }
        public decimal DefaultUnitCost { get; set; }
        public decimal DefaultAmount { get; set; }
        public int PriceAddedFor { get; set; }
        public long LotId { get; set; }
        public string LotType { get; set; }
        public decimal FreeQuantity { get; set; }
        public decimal AmountExcTax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal PriceExcTax { get; set; }
        public decimal AmountIncTax { get; set; }
        public long Under { get; set; }
        public int UnitAddedFor { get; set; }
        public long LotIdForLotNoChecking { get; set; }
        public string LotTypeForLotNoChecking { get; set; }
        public string ComboId { get; set; }
        public bool IsComboItems { get; set; }
        public decimal QuantitySold { get; set; }
        public decimal ComboPerUnitQuantity { get; set; }
        public DateTime? WarrantyExpiryDate { get; set; }
        public decimal ExtraDiscount { get; set; }
        public long ItemCodeId { get; set; }
        public long TaxExemptionId { get; set; }
        public decimal TotalTaxAmount { get; set; }
    }

    public class ClsSalesQuotationDetailsVm
    {
        public long SalesQuotationDetailsId { get; set; }
        public long SalesQuotationId { get; set; }
        public long ItemId { get; set; }
        public long ItemDetailsId { get; set; }
        public decimal Quantity { get; set; }
        public long TaxId { get; set; }
        public string DiscountType { get; set; }
        public decimal Discount { get; set; }
        public decimal UnitCost { get; set; }
        public decimal PriceIncTax { get; set; }
        public string OtherInfo { get; set; }
        public long CompanyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long AddedBy { get; set; }
        public DateTime AddedOn { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ItemName { get; set; }
        public string VariationName { get; set; }
        public string SKU { get; set; }
        public string Tax { get; set; }
        public decimal TaxPercent { get; set; }
        public decimal PurchaseIncTax { get; set; }
        public decimal PurchaseExcTax { get; set; }
        public DateTime SalesDate { get; set; }
        public decimal SalesReturnAmount { get; set; }
        public decimal SalesReturnQuantity { get; set; }
        public long SalesReturnDetailsId { get; set; }
        //public string StockDeductionIds { get; set; }
        public IList<ClsStockDeductionIds> StockDeductionIds { get; set; }
        public decimal QuantityRemaining { get; set; }
        public string ProductType { get; set; }
        public decimal AvailableQuantity { get; set; }
        public string IpAddress { get; set; }
        public string Browser { get; set; }
        public string Platform { get; set; }
        public decimal DefaultUnitCost { get; set; }
        public decimal DefaultAmount { get; set; }
        public int PriceAddedFor { get; set; }
        public long UnitId { get; set; }
        public long SecondaryUnitId { get; set; }
        public long TertiaryUnitId { get; set; }
        public long QuaternaryUnitId { get; set; }
        public string UnitShortName { get; set; }
        public string SecondaryUnitShortName { get; set; }
        public string TertiaryUnitShortName { get; set; }
        public string QuaternaryUnitShortName { get; set; }
        public decimal UToSValue { get; set; }
        public decimal SToTValue { get; set; }
        public decimal TToQValue { get; set; }
        public bool AllowDecimal { get; set; }
        public bool SecondaryUnitAllowDecimal { get; set; }
        public bool TertiaryUnitAllowDecimal { get; set; }
        public bool QuaternaryUnitAllowDecimal { get; set; }
        public string Customer { get; set; }
        public string TaxType { get; set; }
        public decimal SalesIncTax { get; set; }
        public decimal SalesExcTax { get; set; }
        public long LotId { get; set; }
        public string LotType { get; set; }
        public string LotNo { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string InvoiceNo { get; set; }
        public string Name { get; set; }
        public string Supplier { get; set; }
        public string PurchaseInvoiceNo { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public string VariationDetails { get; set; }
        public long BranchId { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public long CategoryId { get; set; }
        public long SubCategoryId { get; set; }
        public long SubSubCategoryId { get; set; }
        public long BrandId { get; set; }
        public long CustomerGroupId { get; set; }
        public string Type { get; set; }
        public decimal FreeQuantity { get; set; }
        public decimal AmountExcTax { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal PriceExcTax { get; set; }
        public decimal AmountIncTax { get; set; }
        public long WarrantyId { get; set; }
        public decimal SalesReturnUnitCost { get; set; }
        public decimal GrandTotal { get; set; }
        public DateTime PurchaseFromDate { get; set; }
        public DateTime PurchaseToDate { get; set; }
        public DateTime SalesFromDate { get; set; }
        public DateTime SalesToDate { get; set; }
        public long CustomerId { get; set; }
        public long SupplierId { get; set; }
        public long Under { get; set; }
        public decimal FreeQuantityReturned { get; set; }
        public int QuantityReturnedPriceAddedFor { get; set; }
        public bool EnableImei { get; set; }
        public int UnitAddedFor { get; set; }
        public string Unit { get; set; }
        public decimal Amount { get; set; }
        public bool IsManageStock { get; set; }
        public long DivId { get; set; }
        public long LotIdForLotNoChecking { get; set; }
        public string LotTypeForLotNoChecking { get; set; }
        public string ComboId { get; set; }
        public bool IsComboItems { get; set; }
        public string Domain { get; set; }
        public decimal QuantitySold { get; set; }
        public decimal ComboPerUnitQuantity { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobileNo { get; set; }
        public string SupplierName { get; set; }
        public string SupplierMobileNo { get; set; }
        public string BranchName { get; set; }
        public string UnitName { get; set; }
        public decimal QuantityReturned { get; set; }
        public long PurchaseId { get; set; }
        public List<ClsComboItems> ComboItems { get; set; }
        public decimal ReturnedAmountIncTax { get; set; }
        public decimal ReturnedQuantity { get; set; }
        public DateTime WarrantyExpiryDate { get; set; }
        public string Duration { get; set; }
        public long DurationNo { get; set; }
        public int WarrantyExpiryTimeLeft { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public decimal ExtraDiscount { get; set; }
        public long SalesOrderDetailsId { get; set; }
        public long SalesProformaDetailsId { get; set; }
        public long SalesDetailsId { get; set; }
        public long ItemCodeId { get; set; }
        public long TaxExemptionId { get; set; }
        public string ItemType { get; set; }
        public DateTime? LotManufacturingDate { get; set; }
        public DateTime? LotExpiryDate { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public string ProductImage { get; set; }
    }
}