using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EquiBillBook.Models
{
    [Table("public.tblUser")]
    public class ClsUser
    {
        [Key]
        public long UserId { get; set; }
        public long UserRoleId { get; set; }
        public long UserGroupId { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string AltMobileNo { get; set; }
        public long ReligionId { get; set; }
        public DateTime? DOB { get; set; }
        public string Gender { get; set; }
        public string BusinessName { get; set; }
        public string TaxNo { get; set; }
        public string Notes { get; set; }
        public bool IsShippingAddressDifferent { get; set; }
        public string ProfilePic { get; set; }
        public decimal CommissionPercent { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OpeningBalance { get; set; }
        //public int PayTermNo { get; set; }
        //public int PayTerm { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long AddedBy { get; set; }
        public DateTime AddedOn { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool IsCompany { get; set; }
        public long CompanyId { get; set; }
        public DateTime ExpiryDate { get; set; }
        public DateTime JoiningDate { get; set; }
        public string UserType { get; set; }
        //public string BranchIds { get; set; }
        public long TaxId { get; set; }
        public long CurrencyId { get; set; }
        public int WhitelabelType { get; set; }
        public long Under { get; set; }
        public decimal AdvanceBalance { get; set; }
        public bool IsWalkin { get; set; }
        public long ReferralId { get; set; }
        public string ReferralCode { get; set; }
        public long ResellerId { get; set; }
        public string IdProof { get; set; }
        public decimal LedgerDiscount { get; set; }
        public bool IsRootAccount { get; set; }
        public string BatchNo { get; set; }
        public long AccountId { get; set; }
        public long JournalAccountId { get; set; }
        public long PaymentTermId { get; set; }
        public long PlaceOfSupplyId { get; set; }
        public long SourceOfSupplyId { get; set; }
        public int IsBusinessRegistered { get; set; }
        public string GstTreatment { get; set; }
        public long BusinessRegistrationNameId { get; set; }
        public string BusinessRegistrationNo { get; set; }
        public string BusinessLegalName { get; set; }
        public string BusinessTradeName { get; set; }
        public string PanNo { get; set; }
        public long TaxPreferenceId { get; set; }
        public long TaxExemptionId { get; set; }
        public long PrefixId { get; set; }
        // Reward Points fields (migrated from tblCustomerRewardPoints)
        public decimal TotalRewardPointsEarned { get; set; }
        public decimal TotalRewardPointsRedeemed { get; set; }
        public decimal AvailableRewardPoints { get; set; }
        public decimal ExpiredRewardPoints { get; set; }
        public DateTime? LastRewardPointsEarnedDate { get; set; }
        public DateTime? LastRewardPointsRedeemedDate { get; set; }
    }

    public class ClsUserVm
    {
        public long UserId { get; set; }
        public long UserRoleId { get; set; }
        public long UserGroupId { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string AltMobileNo { get; set; }
        public long ReligionId { get; set; }
        public DateTime? DOB { get; set; }
        public string Gender { get; set; }
        public string Tagline { get; set; }
        //public string BusinessType { get; set; }
        public string BusinessName { get; set; }
        //public string OwnerName { get; set; }
        public string TaxNo { get; set; }
        public string Notes { get; set; }
        public long CurrencyId { get; set; }
        public long CityId { get; set; }
        public long StateId { get; set; }
        public long CountryId { get; set; }
        //public long Zipcode { get; set; }
        //public string Address { get; set; }
        //public string AltAddress { get; set; }
        public string ProfilePic { get; set; }
        public decimal CommissionPercent { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OpeningBalance { get; set; }
        //public int PayTermNo { get; set; }
        //public int PayTerm { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long AddedBy { get; set; }
        public DateTime AddedOn { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool IsCompany { get; set; }
        public long CompanyId { get; set; }
        public DateTime ExpiryDate { get; set; }
        public string Token { get; set; }
        public long LoginDetailsId { get; set; }
        public string UserType { get; set; }
        public bool IsRememberMe { get; set; }
        public DateTime JoiningDate { get; set; }
        public int PageSize { get; set; }
        public int PageIndex { get; set; }
        public string Search { get; set; }
        public long AltCityId { get; set; }
        public long AltStateId { get; set; }
        //public long AltCountryId { get; set; }
        public string Type { get; set; }
        //public long AltZipcode { get; set; }
        public string FileExtensionProfilePic { get; set; }
        public string FileExtensionIdProof { get; set; }
        public string RoleName { get; set; }
        public string OldPassword { get; set; }
        public string CPassword { get; set; }
        //public string BranchIds { get; set; }
        public string[] Branchs { get; set; }
        public string Title { get; set; }
        public long BranchId { get; set; }
        public string ReligionName { get; set; }
        public bool IsLoggedOut { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public decimal TotalSales { get; set; }
        public decimal TotalSalesPaid { get; set; }
        public decimal TotalSalesDue { get; set; }
        public decimal TotalSalesReturn { get; set; }
        public decimal TotalSalesReturnPaid { get; set; }
        public decimal TotalSalesReturnDue { get; set; }
        public decimal TotalPurchase { get; set; }
        public decimal TotalPurchasePaid { get; set; }
        public decimal TotalPurchaseDue { get; set; }
        public decimal TotalPurchaseReturn { get; set; }
        public decimal TotalPurchaseReturnPaid { get; set; }
        public decimal TotalPurchaseReturnDue { get; set; }
        public long TotalQuantity { get; set; }
        //public string Branch { get; set; }
        public string AddedByCode { get; set; }
        public string ModifiedByCode { get; set; }
        public bool IsShippingAddressDifferent { get; set; }
        public string IpAddress { get; set; }
        public string Browser { get; set; }
        public string Platform { get; set; }
        public string CurrencySymbol { get; set; }
        public string ContactPersonId { get; set; }
        public long TaxId { get; set; }
        public string Otp { get; set; }
        public string CEmailId { get; set; }
        public string OldEmailId { get; set; }
        public List<ClsAddressVm> Addresses { get; set; }
        public long TimeZoneId { get; set; }
        public string Tax { get; set; }
        public string UserGroup { get; set; }
        public string DialingCode { get; set; }
        public string CurrencyCode { get; set; }
        public long UserCurrencyMapId { get; set; }
        public List<ClsUserImport> UserImports { get; set; }
        public int WhitelabelType { get; set; }
        public long Under { get; set; }
        public string Domain { get; set; }
        public string DefaultCurrencySymbol { get; set; }
        public decimal ExchangeRate { get; set; }
        public long CompetitorId { get; set; }
        public decimal AdvanceBalance { get; set; }
        public bool IsWalkin { get; set; }
        public string PaymentType { get; set; }
        public long CustomerId { get; set; }
        public long SupplierId { get; set; }
        public string CurrencyName { get; set; }
        public string Country { get; set; }
        public ClsTransactionVm Transaction { get; set; }
        public bool IsAdvance { get; set; }
        public decimal Due { get; set; }
        public long ReferralId { get; set; }
        public string ReferralCode { get; set; }
        public long ResellerId { get; set; }
        public string IdProof { get; set; }
        public string WhitelabelBusinessName { get; set; }
        public string WhitelabelBusinessIcon { get; set; }
        public string WhitelabelFavicon { get; set; }
        public string MarketingLink { get; set; }
        public string ResellerEmailId { get; set; }
        public decimal OpeningBalanceDue { get; set; }
        public decimal LedgerDiscount { get; set; }
        //public ClsUserPaymentVm Payment { get; set; }
        public ClsBranchVm Branch { get; set; }
        public bool IsRootAccount { get; set; }
        public decimal TotalOpeningBalancePaid { get; set; }
        public string BatchNo { get; set; }
        public long AccountId { get; set; }
        public long JournalAccountId { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public decimal OpeningBalanceDebit { get; set; }
        public decimal OpeningBalanceCredit { get; set; }
        public long TotalSalesInvoices { get; set; }
        public long TotalSalesReturnInvoices { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public long SellingPriceGroupId { get; set; }
        public string SellingPriceGroup { get; set; }
        public string PaymentStatus { get; set; }
        public decimal CustomerOpeningBalancePaid { get; set; }
        public decimal SupplierOpeningBalancePaid { get; set; }
        public long TermLengthId { get; set; }
        public long PaymentTermId { get; set; }
        public int Day { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public long PlaceOfSupplyId { get; set; }
        public long SourceOfSupplyId { get; set; }
        public int IsBusinessRegistered { get; set; }
        public string BusinessRegistrationType { get; set; }
        public string GstTreatment { get; set; }
        public long BusinessRegistrationNameId { get; set; }
        public string BusinessRegistrationNo { get; set; }
        public string BusinessLegalName { get; set; }
        public string BusinessTradeName { get; set; }
        public string PanNo { get; set; }
        public long TaxPreferenceId { get; set; }
        public long TaxExemptionId { get; set; }
        public long PrefixId { get; set; }
        public string TaxPreference { get; set; }
        public string TaxExemptionType { get; set; }
        public bool ShowAllStates { get; set; }
        public string UnitType { get; set; }
        public string PaymentTerm { get; set; }
        public int TotalPurchaseInvoices { get; set; }
        public decimal TotalAmountRemaining { get; set; }
        public bool ShowAllCities { get; set; }
    }

    public class ClsUserImport
    {
        public string UserType { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string AltMobileNo { get; set; }
        public string BusinessName { get; set; }
        public DateTime? DOB { get; set; }
        public DateTime? JoiningDate { get; set; }
        public string UserGroup { get; set; }
        public string TaxName { get; set; }
        public string TaxNo { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OpeningBalance { get; set; }
        //public int PayTermNo { get; set; }
        //public int PayTerm { get; set; }
        public string PaymentTerm { get; set; }
        public string CurrencyName { get; set; }
        public string BranchNames { get; set; }
        //public string CountryName { get; set; }
        public string BillingCustomerName { get; set; }
        public string BillingMobileNo { get; set; }
        public string BillingAltMobileNo { get; set; }
        public string BillingLandmark { get; set; }
        public string BillingCountryName { get; set; }
        public string BillingStateName { get; set; }
        public string BillingCityName { get; set; }
        public long BillingZipcode { get; set; }
        public string BillingAddress { get; set; }
        public string ShippingCustomerName { get; set; }
        public string ShippingName { get; set; }
        public string ShippingMobileNo { get; set; }
        public string ShippingEmailId { get; set; }
        public string ShippingAltMobileNo { get; set; }
        public string ShippingLandmark { get; set; }
        public string ShippingCountryName { get; set; }
        public string ShippingStateName { get; set; }
        public string ShippingCityName { get; set; }
        public long ShippingZipcode { get; set; }
        public string ShippingAddress { get; set; }
        //public string Address { get; set; }
        //public string StateName { get; set; }
        //public string CityName { get; set; }
        //public long Zipcode { get; set; }
        //public string AltCountryName { get; set; }
        //public string AltAddress { get; set; }
        //public string AltStateName { get; set; }
        //public string AltCityName { get; set; }
        //public long AltZipcode { get; set; }
        public bool IsShippingAddressDifferent { get; set; }
        public bool IsWalkin { get; set; }
        public long ReferralId { get; set; }
        public string ReferralCode { get; set; }
        public long ResellerId { get; set; }
        public string IdProof { get; set; }
        public decimal LedgerDiscount { get; set; }
        public string PlaceOfSupply { get; set; }
        public string SourceOfSupply { get; set; }
        public bool IsBusinessRegistered { get; set; }
        public string GstTreatment { get; set; }
        public long BusinessRegistrationName { get; set; }
        public string BusinessRegistrationNo { get; set; }
        public string BusinessLegalName { get; set; }
        public string BusinessTradeName { get; set; }
        public string PanNo { get; set; }
        public string TaxPreference { get; set; }
        public string TaxExemptionReason { get; set; }
        public string GSTIN { get; set; }
    }

}